export {default as Home} from './home/Home'
export {default as ProductList} from './productList/ProductList'
export {default as SingleProduct} from './singleProduct/SingleProduct'
export {default as Register} from './register/Register'
export {default as Login} from './login/Login'
export {default as Cart} from './cart/Cart'